Added views
VasuLief/ice pull request #3
Opened 2017-04-26 20:12 UTC by VasuLief

2017-04-26 20:40 UTC, Kadrei requested changes

2017-04-26 20:40 UTC, Kadrei commented on src/apps/main/index.js
> +    <App store={store} />
wieso `div` drum?

2017-04-26 20:49 UTC, Kadrei requested changes

2017-04-26 20:49 UTC, Kadrei commented on src/index.js
>  renderApplication(document.getElementById('root'))
In der .editorconfig steht
`insert_final_newline = true`

d.h. wird beim nächsten mal wieder zurückgechanged. richte dir am besten editorconfig und eslint in deiner IDE ein

2017-04-26 20:49 UTC, Kadrei commented on src/features/api/mocks/products.json
> +    "image": "product1.svg",
zum testen der bilder könnte man auf [Lorem Pixel](http://lorempixel.com/) zurückgreifen

2017-04-26 20:49 UTC, Kadrei commented on src/components/userlist.js
> +    const teamUsers = this.props.users.filter(user => user.team_id === this.props.team)
kannst es auch chainen: `this.props.users.filter(...).map(...)`

2017-04-26 20:49 UTC, Kadrei commented on src/components/user.js
> +      <p>
ist `<p>` und `<div>` nicht doppelt gemoppelt?

2017-04-26 20:49 UTC, Kadrei commented on src/components/teamlist.js
> +  onClick (id) {
`.bind(this)`

2017-04-26 20:49 UTC, Kadrei commented on src/components/product.js
> +      <p>Product: {this.props.name}</p>
`<div>`und `<p>` doppelt gemoppelt? (beides blockelemente)

2017-04-26 20:49 UTC, Kadrei commented on src/components/userlist.js
> +  onClick (id) {
`bind(this)`

2017-07-05 14:51 UTC, VasuLief commented on src/index.js
>  renderApplication(document.getElementById('root'))
fixed

2017-07-05 14:52 UTC, VasuLief commented on src/features/api/mocks/products.json
> +    "image": "product1.svg",
Gute Idee für später

2017-07-05 18:00 UTC, Kadrei approved these changes

2017-07-05 18:00 UTC, merged